version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_rest
    ports:
      - "3306:3306"
    networks:
      - my_network

  nodeapp:
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=api_rest
      - DB_PORT=3306
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: [ "sh", "-c", "sleep 10 && npm start" ]
    networks:
      - my_network

networks:
  my_network:
